"""Initial migration

Revision ID: 3c1e09f76224
Revises: 
Create Date: 2025-10-22 15:42:38.437969

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3c1e09f76224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
