"""Add name and remove password from User model

Revision ID: a8d45b4af229
Revises: ad52160624e9
Create Date: 2025-11-12 02:09:08.205346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d45b4af229'
down_revision: Union[str, Sequence[str], None] = 'ad52160624e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new temporary table with the desired schema
    op.create_table(
        'users_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False), # Email should be NOT NULL
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), # Make NOT NULL with default
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')), # Make NOT NULL with default
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    # Copy data from the old 'users' table to 'users_new'
    # Ensure 'is_active' and 'is_admin' get their default values if they were NULL
    op.execute(
        """
        INSERT INTO users_new (id, email, name, is_active, is_admin)
        SELECT id, email, name, COALESCE(is_active, TRUE), COALESCE(is_admin, FALSE) FROM users
        """
    )

    # Drop the old 'users' table
    op.drop_table('users')

    # Rename the new table to 'users'
    op.rename_table('users_new', 'users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new temporary table 'users_old' with the original schema
    op.create_table(
        'users_old',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False), # Email should be NOT NULL
        sa.Column('password', sa.String(), nullable=True), # Original column
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), # Make NOT NULL with default
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')), # Make NOT NULL with default
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    # Copy data from the current 'users' table to 'users_old'
    op.execute(
        """
        INSERT INTO users_old (id, email, is_active, is_admin)
        SELECT id, email, COALESCE(is_active, TRUE), COALESCE(is_admin, FALSE) FROM users
        """
    )

    # Drop the current 'users' table
    op.drop_table('users')

    # Rename the temporary table to 'users'
    op.rename_table('users_old', 'users')
    # ### end Alembic commands ###
